-- phpMyAdmin SQL Dump
-- version 5.2.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Apr 28, 2026 at 06:46 PM
-- Server version: 11.8.6-MariaDB-log
-- PHP Version: 7.2.34

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `u119871985_cafeteriafanny`
--

-- --------------------------------------------------------

--
-- Table structure for table `events`
--

CREATE TABLE `events` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `subtitle` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `full_description` text NOT NULL,
  `event_date` varchar(100) NOT NULL,
  `event_yyyymm` int(6) DEFAULT NULL,
  `location` varchar(255) NOT NULL,
  `attendees` varchar(100) NOT NULL,
  `image` varchar(255) NOT NULL,
  `banner_image` varchar(255) NOT NULL,
  `is_active` tinyint(1) DEFAULT 1,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `events`
--

INSERT INTO `events` (`id`, `title`, `subtitle`, `description`, `full_description`, `event_date`, `location`, `attendees`, `image`, `banner_image`, `is_active`, `created_at`, `updated_at`) VALUES
(1, 'Evento La Rural', 'Congreso Argentino de Cardiología (SAC)', 'Servicio de café premium para el prestigioso Congreso Argentino de Cardiología, uno de los eventos médicos más importantes del año.', 'El Congreso Argentino de Cardiología (SAC) reunió a más de 500 profesionales de la salud en La Rural, donde tuvimos el honor de brindar nuestro servicio de café premium durante los tres días del evento.\n\nInstalamos múltiples estaciones de café estratégicamente ubicadas en diferentes áreas del predio, incluyendo el hall principal, las salas de conferencias y las zonas de networking. Cada estación contó con máquinas de última generación y un barista profesional dedicado a preparar café de especialidad para los asistentes.\n\nOfrecimos una amplia variedad de opciones, desde espressos intensos hasta capuchinos suaves, además de alternativas sin lactosa y descafeinadas. La presentación fue impecable, con vajilla elegante y un servicio personalizado que recibió excelentes comentarios de los organizadores y participantes.', '15 al 17 de Octubre, 2025', 'La Rural - Predio Ferial, Buenos Aires', '500+ profesionales', '/assets/images/laRural/caratula.jpg', '/assets/images/laRural/caratula.jpg', 1, '2025-10-23 14:14:02', '2025-10-28 17:41:09'),
(2, 'Brubank en ECI 2022', 'Ciudad Universitaria UBA', 'Evento académico de referencia en informática con alta convocatoria de estudiantes y profesionales IT. Aroma a Café acompañó con estaciones de café premium, generando espacios de networking y pausa durante toda la jornada.', 'Evento destacado en el ámbito académico y tecnológico, la 35.ª edición de la Escuela de Ciencias Informáticas (ECI) reunió a estudiantes, profesionales, investigadores y referentes de la industria IT en un entorno de aprendizaje, networking e innovación. Desarrollado del 25 al 29 de julio de 2022 en el moderno Pabellón Cero + Infinito de Ciudad Universitaria (UBA), el evento ofreció una agenda intensiva con conferencias, workshops y espacios de intercambio sobre tendencias en informática, desarrollo de software, inteligencia artificial y nuevas tecnologías.\r\nEn este contexto de alta participación y dinamismo, Brubank se posicionó como uno de los patrocinadores principales en la categoría Diamond, aportando visibilidad, propuestas de valor y experiencias para los asistentes. Como parte de la experiencia integral del evento, se dispusieron servicios de coffee break de alta calidad, diseñados para acompañar los momentos de pausa, fomentar el networking y mejorar la experiencia general de los participantes.\r\nAroma a  Café se integró perfectamente a la dinámica del evento, ofreciendo café premium de manera continua, rápida y eficiente durante toda la jornada. Las estaciones de café se convirtieron en puntos de encuentro clave, donde asistentes y expositores pudieron disfrutar de bebidas de especialidad en un entorno cómodo y profesional, elevando el estándar del servicio y aportando un valor diferencial a la experiencia del evento.\r\n', '25 al 29 de Julio, 2022', 'Pabellón Cero + Infinito de Ciudad Universitaria (UBA)', '150 invitados', '/assets/images/brubank/portada.jpg', '/assets/images/brubank/portada.jpg', 1, '2026-04-28 14:14:02', '2026-04-28 21:50:55'),
(3, 'Congreso Argentino de Oftalmología 2026', 'Laboratorio Roche', 'Encuentro médico-científico de primer nivel con participación de especialistas y referentes del sector salud. Aroma a Café brindó un servicio continuo y de alta calidad, elevando la experiencia de los asistentes. ', 'Evento de gran relevancia dentro del ámbito médico-científico, el Congreso Argentino de Oftalmología 2026 reunió a especialistas, investigadores, profesionales de la salud y referentes de la industria farmacéutica en un espacio dedicado a la actualización, la innovación y el intercambio de conocimientos en salud visual.\r\nOrganizado en las instalaciones del Hotel Hilton Buenos Aires, en el exclusivo barrio de Puerto Madero, el evento se desarrolló durante los días 15, 16 y 17 de abril de 2026, ofreciendo un entorno moderno, confortable y altamente profesional para la realización de conferencias, simposios y actividades de networking.\r\nLaboratorios Roche participó como uno de los protagonistas del congreso, presentando avances, soluciones terapéuticas y propuestas innovadoras en el campo de la oftalmología, fortaleciendo su posicionamiento dentro del sector y generando vínculos estratégicos con la comunidad médica.\r\nEn este contexto, Aroma a Café acompañó el desarrollo del evento, brindando una experiencia premium a lo largo de toda la jornada. Se instalaron estaciones de café estratégicamente ubicadas, pensadas para facilitar el acceso de los asistentes durante los intervalos entre actividades, promoviendo espacios de encuentro, conversación y networking.\r\nLas máquinas, de última tecnología, garantizaron un servicio ágil, continuo y de alta calidad, ofreciendo una variedad de bebidas que se adaptaron a las preferencias de los participantes. De esta manera, contribuimos a elevar la experiencia general del evento, aportando comodidad, eficiencia y un valor diferencial en cada pausa.\r\n', '15, 16 y 17 de abril de 2026', 'Hotel Hilton, Puerto Madero', '200 ejecutivos', '/assets/images/roche/portada.jpg', '/assets/images/roche/portada.jpg', 1, '2025-10-23 14:14:02', '2026-04-28 15:39:57'),
(4, 'NotCo – La Rural 2022', 'Presentacion de la linea NotMenu', 'Evento gastronómico innovador enfocado en propuestas plant-based. Aroma a Café complementó la experiencia del stand con café premium, acompañando degustaciones y momentos de interacción.', 'Evento orientado a la innovación en gastronomía y consumo consciente, realizado los días 4 y 5 de mayo de 2022 en el predio de La Rural, uno de los espacios feriales más emblemáticos de la ciudad. La propuesta reunió a marcas, emprendedores y profesionales del sector alimenticio interesados en las nuevas tendencias, especialmente en el crecimiento de alternativas basadas en plantas y experiencias gastronómicas sustentables.\r\nDentro de este marco, el stand de NotCo se destacó por su enfoque innovador y su gran convocatoria. La marca presentó su línea “NotMenu”, orientada a cafeterías y espacios gastronómicos que buscan incorporar opciones plant-based sin resignar sabor ni calidad. Entre los productos protagonistas se encontraron el NotLatte —una alternativa vegetal al café con leche tradicional— junto con una variedad de pastelería elaborada a base de plantas, como cookies, brownies y budines, que generaron gran interés entre los asistentes.\r\nEl stand fue diseñado como un espacio dinámico y atractivo, donde los visitantes pudieron degustar los productos, conocer más sobre la propuesta de la marca y experimentar de primera mano la calidad de estas alternativas. La combinación de innovación, sabor y una estética moderna posicionó a NotCo como uno de los puntos más concurridos del evento.\r\nAcompañando esta experiencia, Aroma a Café estuvo presente, garantizando un flujo constante de bebidas calientes de alta calidad. La estación de café no solo complementó la propuesta gastronómica del stand, sino que también se convirtió en un punto clave de encuentro, favoreciendo la interacción entre los asistentes y potenciando la experiencia general del evento. La eficiencia del servicio, sumada a la calidad del café ofrecido, aportó un valor diferencial que elevó aún más la percepción del espacio.\r\n', '4 y 5 de Mayo,2022', 'Predio La Rural', '100 ejecutivos', '/assets/images/notco/portada.jpg', '/assets/images/notco/portada.jpg', 1, '2025-10-23 14:14:02', '2026-04-28 16:04:51'),
(5, 'Intersec Buenos Aires 2022\r\n', 'Stand de la Empresa Dahua Technology', 'Feria líder en seguridad y tecnología con demostraciones en vivo y alto tráfico de visitantes. Aroma a Café aportó un punto de encuentro clave dentro del stand, optimizando la experiencia del público.', 'Evento de referencia en la industria de la seguridad integral, Intersec Buenos Aires 2022 reunió a empresas, profesionales y especialistas en tecnologías de protección, videovigilancia, control de accesos y soluciones inteligentes. Desarrollado del 24 al 26 de agosto de 2022 en La Rural, el encuentro se consolidó como un espacio clave para la presentación de innovaciones, generación de negocios y actualización profesional dentro del sector.\r\nEntre los expositores más destacados se encontró Dahua Technology, uno de los líderes globales en soluciones de seguridad electrónica. Su stand captó gran atención por la demostración en vivo de tecnologías avanzadas, incluyendo sistemas de videovigilancia con inteligencia artificial, reconocimiento facial, monitoreo en tiempo real y soluciones integrales para ciudades inteligentes y entornos corporativos.\r\nEl espacio de Dahua fue concebido como una experiencia interactiva, donde los asistentes pudieron conocer en profundidad el funcionamiento de sus productos, participar de demostraciones técnicas y recibir asesoramiento personalizado por parte de especialistas. Este enfoque permitió generar un alto nivel de engagement, posicionando a la marca como uno de los puntos más visitados de la exposición.\r\nEn este contexto dinámico y de alta circulación, Aroma a Café aportó un valor diferencial dentro del stand, acompañando la experiencia de los visitantes. Nuestro servicio de café ofreció bebidas de calidad premium de forma continua, facilitando momentos de pausa y networking en un entorno profesional. La combinación de tecnología, atención y servicio eficiente contribuyó a mejorar la experiencia general del espacio, transformándolo en un punto de encuentro cómodo y atractivo para clientes y potenciales socios.\r\n', '24 al 26 de Agosto, 2022', 'Predio de La Rural', '1000+ visitantes', '/assets/images/intersec/portada.jpg', '/assets/images/intersec/portada.jpg', 1, '2025-10-23 14:14:02', '2026-04-28 12:50:55'),
(6, 'Raza Pampa 2022 ', 'Evento en La Rural', 'Evento corporativo de gran escala que reunió a destacadas empresas de diversos sectores, cada una con su propio stand para presentar servicios, generar contactos y fortalecer vínculos comerciales. Aroma a Café acompañó a Raza Pampa brindando servicio de café premium, creando espacios ideales para reuniones y networking. \r\n', 'Evento corporativo de gran escala realizado en noviembre de 2022 en La Rural, que reunió a importantes empresas de diversos sectores en un entorno diseñado para la exposición, el networking y la generación de oportunidades comerciales. Lejos de un enfoque tradicional, el evento se consolidó como una plataforma multisectorial donde cada compañía contó con su propio stand, presentando sus servicios, soluciones y propuestas de valor ante un público profesional y altamente segmentado.\r\nLa dinámica del evento estuvo centrada en la interacción directa entre marcas y asistentes, favoreciendo reuniones, demostraciones y espacios de intercambio que impulsaron vínculos estratégicos y संभावidades de negocio. La diversidad de rubros presentes —desde tecnología y servicios hasta consumo masivo y soluciones corporativas— aportó riqueza y dinamismo, convirtiendo al evento en un punto de encuentro clave para profesionales, empresarios y tomadores de decisión.\r\nLos stands, cuidadosamente diseñados, ofrecieron experiencias personalizadas, con presentaciones en vivo, asesoramiento comercial y propuestas innovadoras que captaron la atención del público. Este enfoque permitió maximizar la visibilidad de cada empresa y potenciar su posicionamiento dentro de un entorno altamente competitivo.\r\nEn este contexto de alto flujo y constante interacción, Aroma a Café formó parte del evento brindando su servicio  de café en el stand de  Raza Pampa. La estacion de café premium se convirtió en punto clave para reuniones informales, pausas activas y momentos de networking, acompañando la dinámica del evento de forma natural.\r\nGracias a un servicio ágil, continuo y de alta calidad, Aroma a Café aportó un valor diferencial, mejorando la experiencia general de expositores y visitantes. El café no solo funcionó como un complemento, sino como un facilitador de encuentros, contribuyendo a generar un ambiente más cómodo, profesional y propicio para el desarrollo de relaciones comerciales.\r\n', 'Noviembre, 2022', 'Predio La Rural', '+500 participantes', '/assets/images/raza/portada.jpg', '/assets/images/raza/portada.jpg', 1, '2025-10-23 14:14:02', '2026-04-28 13:50:55'),
(7, 'Camino Federal hacia la Cumbre ', 'Jornada en Legislatura CABA', 'Evento institucional previo a la Cumbre de Alcaldes C40, con foco en sostenibilidad y políticas urbanas. Aroma a Café aportó un servicio elegante y eficiente, acorde al nivel del encuentro. \r\n', 'Evento institucional de gran relevancia en la agenda climática y de gestión urbana, “Camino Federal hacia la Cumbre” se desarrolló en el imponente Palacio de la Legislatura de la Ciudad de Buenos Aires, específicamente en su elegante Hall de Honor, un espacio emblemático que aportó un marco solemne y representativo para el encuentro.\r\nEsta jornada formó parte de las actividades previas a la Cumbre Mundial de Alcaldes de C40 2022, realizada en Buenos Aires en octubre de 2022, y tuvo como objetivo reunir a referentes de distintas provincias, funcionarios, especialistas y actores clave para debatir y construir una agenda federal en torno al cambio climático, el desarrollo sostenible y las políticas públicas urbanas.\r\nEl evento se caracterizó por un alto nivel de participación institucional y técnica, con paneles de discusión, presentaciones y espacios de intercambio orientados a alinear estrategias entre gobiernos locales y potenciar el rol de las ciudades en la acción climática global. La diversidad de voces y la calidad de los contenidos posicionaron a esta jornada como un punto de partida fundamental hacia la cumbre internacional.\r\nEn este entorno formal y de gran convocatoria, el servicio de Aroma a Café se integró de manera armónica, aportando una experiencia de coffee break acorde al nivel del evento acompañando los momentos de pausa entre actividades, facilitando el networking y la interacción entre los asistentes.\r\nLa calidad del café, junto con un servicio ágil y discreto, permitió ofrecer una experiencia premium que complementó el carácter institucional del encuentro. De esta manera, Aroma a Café contribuyó a generar un ambiente más confortable y propicio para el diálogo, sumando un valor diferencial en un evento de alto perfil político y social. \r\n', 'Octubre, 2022', 'Legislatura de la Ciudad de Buenos Aires', '250 invitados', '/assets/images/legislatura/mesa1.jpg', '/assets/images/legislatura/mesa1.jpg', 1, '2025-10-23 14:14:02', '2026-04-28 21:50:55'),
(8, 'Casamiento – San Miguel del Monte \r\n', 'Evento Social', 'Celebración privada de la comunidad judía en un entorno natural y exclusivo. Aroma a Café acompañó con estaciones de café premium, sumando calidez y calidad a un momento especial. \r\n', 'Evento social de carácter privado, realizado el 30 de abril de 2022 en San Miguel del Monte, en el marco de la celebración de un casamiento perteneciente a la comunidad judía. La jornada se desarrolló en un entorno natural y exclusivo, ideal para este tipo de encuentros, donde la combinación de tradición, emoción y celebración dio lugar a una experiencia única para los novios y sus invitados.\r\nLa ceremonia y posterior festejo estuvieron marcados por los valores y costumbres propias de la cultura judía, integrando momentos simbólicos, música y una propuesta gastronómica especialmente cuidada. La ambientación del evento acompañó este espíritu, con detalles elegantes y una organización pensada para garantizar comodidad, fluidez y disfrute a lo largo de toda la jornada.\r\nEn este contexto, donde cada detalle resulta clave para lograr una experiencia memorable, Aroma a Café formó parte del evento brindando su servicio  de café. La estación fue instalada de manera estratégica para acompañar tanto la recepción como los momentos posteriores a la cena, ofreciendo a los invitados una propuesta de bebidas calientes de calidad premium.\r\nEl servicio se adaptó a la dinámica del evento, asegurando rapidez, eficiencia y una presentación acorde al nivel de la celebración. De esta manera, Aroma a Café aportó un valor diferencial, generando espacios de encuentro y distensión donde los invitados pudieron disfrutar de un excelente café, complementando una experiencia ya de por sí especial y significativa.\r\n', '30 de Abril, 2022', 'Salón de Gala', '200 invitados', '/assets/images/casamiento/portada.jpg', '/assets/images/casamiento/portada.jpg', 1, '2025-10-23 14:14:02', '2026-04-28 17:45:48');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `events`
--
ALTER TABLE `events`
  ADD PRIMARY KEY (`id`),
  ADD KEY `idx_event_yyyymm` (`event_yyyymm`),
  ADD KEY `idx_is_active` (`is_active`),
  ADD KEY `idx_created_at` (`created_at`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `events`
--
ALTER TABLE `events`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
